hunter_config(
    SDL2 
    VERSION ${HUNTER_SDL2_VERSION} 
    CMAKE_ARGS
    BUILD_SHARED_LIBS=ON
    CMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT_DIRECTORY}
    CMAKE_LIBRARY_OUTPUT_DIRECTORY=${CMAKE_LIBRARY_OUTPUT_DIRECTORY}
    CMAKE_ARCHIVE_OUTPUT_DIRECTORY=${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}
)
unset(CMAKE_DEBUG_POSTFIX)